version: "3.8"

services:
  mysql:
    image: mysql:9.2.0-oraclelinux9
    environment:
      # [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
      # You need to specify one of the following as an environment variable:
      # - MYSQL_ROOT_PASSWORD
      # - MYSQL_ALLOW_EMPTY_PASSWORD
      # - MYSQL_RANDOM_ROOT_PASSWORD
      # [ERROR] [Entrypoint]: MYSQL_USER="root", MYSQL_USER and MYSQL_PASSWORD are for configuring a regular user and cannot be used for the root user
      # Remove MYSQL_USER="root" and use one of the following to control the root user password:
      # - MYSQL_ROOT_PASSWORD
      # - MYSQL_ALLOW_EMPTY_PASSWORD
      # - MYSQL_RANDOM_ROOT_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: chuongtrinhdaotao
      MYSQL_USER: admin
      MYSQL_PASSWORD: ""
    # command: --sql_mode="STRICT_TRANS_TABLES"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./chuongtrinhdaotao.sql:/docker-entrypoint-initdb.d/chuongtrinhdaotao.sql:ro

  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "5050:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
