version: "3.8"

services:
    mysql:
        image: mysql:9.2.0-oraclelinux9
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: chuongtrinhdaotao
            MYSQL_USER: root
            MYSQL_PASSWORD: ""
        command: --sql_mode="STRICT_TRANS_TABLES"
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./DatabaseServer/ql_cuahanggiay.sql:/docker-entrypoint-initdb.d/ql_cuahanggiay.sql:ro

    phpmyadmin:
        image: phpmyadmin:5.2.2-apache
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: ""
        ports:
            - "5050:80"
        depends_on:
            - mysql

volumes:
    mysql-data:
