server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chuongtrinhdaotao1?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: